configMapGenerator:
  - files:
      - application.yml
    name: "82022401-configmap"
resources:
  - pvc.yaml
patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
  - name:  ceappacr.azurecr.io/82022401
    newTag: "202410140453"
